name: Pull Request

on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize
  merge_group:

permissions:
  id-token: write
  contents: read
  security-events: write
  actions: read

jobs:
  unit-tests:
    uses: ./.github/workflows/unit-tests.yml

  integration-tests:
    uses: ./.github/workflows/integration-tests.yml

  sonarcloud:
    uses: ./.github/workflows/sonar-scan.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  terraform-checks:
    uses: ./.github/workflows/terraform-checks.yml

  checkov:
    uses: ./.github/workflows/checkov.yml

  validation:
    uses: ./.github/workflows/validation.yml

  pull-request:
    name: pull-request
    if: always()
    needs:
      - unit-tests
      - integration-tests
      - sonarcloud
      - terraform-checks
      - checkov
      - validation
    runs-on: ubuntu-latest
    steps:
      - name: Check all jobs succeeded
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
        run: exit 1
